# Generated by Django 4.2.10 on 2024-02-27 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_sentence_syntactic_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='syntactic_analysis',
        ),
    ]
