# Generated by Django 4.2.10 on 2024-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_choice_question_delete_qiangdaitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='syntactic_analysis',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.CharField(max_length=2000),
        ),
    ]
